### ISSUE TITLE
Getting KeyError

### ISSUE THREAD

**Issue by Kehindeajayi01** [DCGM/pero-ocr#54]
I was trying the pero-ocr on a png image with table and text but got the error below. Please, how do I resolve this?

<img width="1099" alt="Screenshot 2023-09-07 at 2 42 19 PM" src="https://github.com/DCGM/pero-ocr/assets/43017928/322098f5-fca8-4dfc-b48d-8205cff444f1">

**Comment by ikiss-fit** [comment]
This problem occurs because the `PAGE_PARSER` section is probably missing in the configuration. This configuration tells the entire processing what to apply to the input data - the entire pipeline consists of four steps: line detection, line cropping, text recognition, and decoding with a language model. For example, sometimes it is only needed to detect text lines or to recognize and decode the text. Look in the `config.ini` file in the archive with the [available trained models](https://github.com/DCGM/pero-ocr/tree/master#available-models).

I assume you are trying to use the PageParser class to process your image. That's OK, but you need to add configuration processing there - look at the [integration code example](https://github.com/DCGM/pero-ocr/tree/master#integration-of-the-pero-ocr-python-module), it's just below the imports. The other option is to use the [prepared user script](https://github.com/DCGM/pero-ocr/tree/master#command-line-application) `parse_folder.py` in the `user_scripts` directory, which starts the processing and all you need to specify is the path to the configuration, the path to the input directories, and the path to the output directories.

Please let me know if there are any other problems or questions.

**Comment by Kehindeajayi01** [comment]
> This problem occurs because the `PAGE_PARSER` section is probably missing in the configuration. This configuration tells the entire processing what to apply to the input data - the entire pipeline consists of four steps: line detection, line cropping, text recognition, and decoding with a language model. For example, sometimes it is only needed to detect text lines or to recognize and decode the text. Look in the `config.ini` file in the archive with the [available trained models](https://github.com/DCGM/pero-ocr/tree/master#available-models).
> 
> I assume you are trying to use the PageParser class to process your image. That's OK, but you need to add configuration processing there - look at the [integration code example](https://github.com/DCGM/pero-ocr/tree/master#integration-of-the-pero-ocr-python-module), it's just below the imports. The other option is to use the [prepared user script](https://github.com/DCGM/pero-ocr/tree/master#command-line-application) `parse_folder.py` in the `user_scripts` directory, which starts the processing and all you need to specify is the path to the configuration, the path to the input directories, and the path to the output directories.
> 
> Please let me know if there are any other problems or questions.

I have downloaded the available model and specified the path to the "config_cpu.ini" file but I am still getting the error below:
<img width="1375" alt="Screenshot 2023-09-11 at 12 09 09 PM" src="https://github.com/DCGM/pero-ocr/assets/43017928/703c3bf2-b479-407e-ae09-22c1c11eebce">

**Comment by michal-hradis** [comment]
I'm not sure what "pero_ocr.py" is, but the error states that "--config_path" is not an argument. Could it be "--config-path"?

**Comment by Kehindeajayi01** [comment]
> I'm not sure what "pero_ocr.py" is, but the error states that "--config_path" is not an argument. Could it be "--config-path"?

I only copied the "prepared user script" provided into a python script and name it "pero_ocr.py". See full code below:


import os
import configparser
import cv2
import numpy as np
from pero_ocr.document_ocr.layout import PageLayout
from pero_ocr.document_ocr.page_parser import PageParser
import argparse
import os

def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--img", help = "path to the image")
    parser.add_argument("--out", help = "path to save the image")
    #parser.add_argument("--config_path", help = "path to the config path")
    args = parser.parse_args()
    return args

args = get_args()
# Read config file.
config_path = "./Users/kehindeajayi01/Downloads/pero_eu_cz_print_newspapers_2022-09-26/config_cpu.ini"             # path to the config_file.ini
config = configparser.ConfigParser()
config.read(config_path)

# Init the OCR pipeline. 
# You have to specify config_path to be able to use relative paths
# inside the config file.
page_parser = PageParser(config, config_path=os.path.dirname(config_path))

# Read the document page image.
input_image_path = img_path = args.img
image = cv2.imread(input_image_path, 1)

# Init empty page content. 
# This object will be updated by the ocr pipeline. id can be any string and it is used to identify the page.
page_layout = PageLayout(id=input_image_path,
     page_size=(image.shape[0], image.shape[1]))

# Process the image by the OCR pipeline
page_layout = page_parser.process_page(image, page_layout)

page_layout.to_pagexml(os.path.join(args.out, 'Mat208.xml')) # Save results as Page XML.
page_layout.to_altoxml(os.path.join(args.out, 'Mat208_alto.xml')) # Save results as ALTO XML.

**Comment by michal-hradis** [comment]
I'm not sure what exactly is the "prepared user script", but your definition os argument config_path is a comment and is not defined in your code.
