### ISSUE TITLE
problem of numpy version

### ISSUE THREAD

**Issue by Jingyi2000** [DCGM/pero-ocr#58]
Hello, when running the Integration of the pero-ocr python module, I encountered a problem with the numpy version, the error showed:

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

If I want to lower the numpy version, scipy, numba, etc. also need to lower the version for compatibility, but many lower versions cannot be installed on my computer. What suggestions do you have? Thanks in advance!

**Comment by ikiss-fit** [comment]
Hi, this issue is fixed in the current develop branch. Next week at the latest, @ibenes plans to create a new release and therefore the changes from the `develop` branch will go to the `master` branch.

If you are working with a local copy of the repository, you can of course change the branch to `develop` and it should work. Just be careful, there are more changes between the `master` and `develop` branches and they can affect integration - the biggest change is the creation of a `core` directory where the `Layout` class definition is, for example.

**Comment by ibenes** [comment]
Dear @Jingyi2000,
it took an academic interpretation of "next week at latest" ;-) but the new version is finally live. In the process, we have removed several other deprecation warnings, allowing for integration of pero-ocr with newer versions of several packages, notably `numba` and `shapely`.
