### ISSUE TITLE
Problem with the pretrained model  not available

### ISSUE THREAD

**Issue by halaneji** [DCGM/pero-ocr#59]
File "/usr/local/lib/python3.9/dist-packages/torch/jit/_serialization.py", line 149, in load
    raise ValueError(f"The provided filename {f} does not exist")  # type: ignore[str-bytes-safe]
ValueError: The provided filename /opt/pero/pero-ocr/ocr_model/checkpoint_646000.ckpt does not exist

**Comment by ikiss-fit** [comment]
I'm not sure what checkpoint you are using (there is no such checkpoint in the available models). Anyway, you need to check if the model exists in that particular location. Otherwise I'm not able to help you without more details (processing configuration, checkpoint information, etc).

**Comment by halaneji** [comment]
Thank you so much for your reply.
I have this files :
ocr_model/
├── checkpoint_646000.ckpt.data-00000-of-00001
├── checkpoint_646000.ckpt.index
├── checkpoint_646000.ckpt.meta
└── ocr_engine.json

and the configuration is 
cat config.ini 
[PAGE_PARSER]
RUN_LAYOUT_PARSER = yes
RUN_LINE_PARSER = yes
RUN_LINE_CROPPER = yes
RUN_OCR = yes
RUN_DECODER = no

[LAYOUT_PARSER]
METHOD = WHOLE_PAGE_REGION

[LINE_PARSER]
METHOD = cnn
#for CNN line engine
MODEL_PATH = ./layout_model/ParseNet_exported

DOWNSAMPLE = 4
USE_CPU = no
PAD = 52
DETECTION_THRESHOLD = 0.2

#for line postprocessing
MERGE_LINES = no
STRETCH_LINES = 0
RESAMPLE_LINES = yes
ORDER_LINES = vertical

[LINE_CROPPER]
INTERP = 2
LINE_SCALE = 1
LINE_HEIGHT = 32

[OCR]
OCR_JSON = ./ocr_model/ocr_engine.json

when I run the docker I have the problem  "ocr_model/checkpoint_646000.ckpt does not exist"

**Comment by ikiss-fit** [comment]
I guess you are using very old models that are probably no longer compatible with the current version of pero-ocr (we used Tensorflow before, now we only use PyTorch). The easiest thing to do is to download the latest available model package and the latest version of pero-ocr that are compatible with each other.

Otherwise, if you insist on using these older versions, the problem is obviously in the wrong paths. You can try setting absolute paths to the required files (MODEL_PATH, OCR_JSON) in the configuration file.

**Comment by halaneji** [comment]
Thank you so much !
solved @ikiss-fit
